### ISSUE TITLE
Server status inquiry failure

### ISSUE THREAD

**Issue by G33kM0bile** [TheONLYGod1/FivemServerStatus#1]
Hi
What am i doing wrong, as i know the server are online, and has players. still, the bot seem unable to find the session from txadmin.. Do i need to open/do something somewhere?

![image](https://user-images.githubusercontent.com/42103659/128597105-1f77e1fd-c61d-4faa-97a6-a5a0b7fadb81.png)

**Comment by TheONLYGod1** [comment]
I am looking into it right now!

**Comment by TheONLYGod1** [comment]
> Hi
> What am i doing wrong, as i know the server are online, and has players. still, the bot seem unable to find the session from txadmin.. Do i need to open/do something somewhere?
> 
> ![image](https://user-images.githubusercontent.com/42103659/128597105-1f77e1fd-c61d-4faa-97a6-a5a0b7fadb81.png)

Can you please join my discord server so we can talk there? https://discord.gg/pAKE2YK

**Comment by PurchasedGaming** [comment]
Sorry, hate to butt in, but your port is incorrect, that port is a TxAdmin Port and not a FiveM port, the default FiveM Port is "30120"

**Comment by TheONLYGod1** [comment]
Issue wasn't updated with needed information so I have closed it. Make sure you are using the default server port not the txtadmin port.
