### ISSUE TITLE
The bot works with my test server, but not on my Main server

### ISSUE THREAD

**Issue by WorldOfApedGaming** [TheONLYGod1/FivemServerStatus#11]
![image](https://user-images.githubusercontent.com/44633197/158426502-8d58c0c3-c707-4806-a9cb-62895b464f4b.png)
![image](https://user-images.githubusercontent.com/44633197/158426692-764d60b0-802b-400e-9257-0b7131236398.png)

**Comment by TheONLYGod1** [comment]
Are both servers hosted on the same hardware/same location?

**Comment by TheONLYGod1** [comment]
Does your host allow out-going connections? aka is their firewall blocking outgoing requests..

**Comment by WorldOfApedGaming** [comment]
No, it doesn't. Can I know how to allow it for a VibeGames server?

**Comment by TheONLYGod1** [comment]
You'd have to ask your host to allow outgoing requests
