### ISSUE TITLE
Functionality Of NPM?

### ISSUE THREAD

**Issue by kingofkingzcd** [TheONLYGod1/FivemServerStatus#12]
what is this `npm i` `npm install` garb? maybe include some kinda walkthrough about that as i have node and everything else installed. also this shit is useless for current times bc everything has ditched steam. which makes using fivemqueue an absolute shit show.

**Comment by TheONLYGod1** [comment]
npm install , or npm i , is used to install dependencies: It will install all the dependencies

Links-To-Read:
https://www.stackchief.com/tutorials/npm%20install%20%7C%20how%20it%20works


As far as I'm aware, the bot still functions regardless of Steams changes. I'm not going to explain the whole functionality of JS to you as you can learn from online tutorials.

**Comment by TheONLYGod1** [comment]
> what is this `npm i` `npm install` garb? maybe include some kinda walkthrough about that as i have node and everything else installed. also this shit is useless for current times bc everything has ditched steam. which makes using fivemqueue an absolute shit show. 

I didn't notice the last bit of the message.... this doesn't rely on Steams API by any means.... and the documentation can not be any clearer on how to set it up. However, if you do not have the basic knowledge in coding / running a nodejs application / ect. then you'll need to do some research online before assuming something you don't know much about.

**Comment by kingofkingzcd** [comment]
> > what is this `npm i` `npm install` garb? maybe include some kinda walkthrough about that as i have node and everything else installed. also this shit is useless for current times bc everything has ditched steam. which makes using fivemqueue an absolute shit show.
> 
> I didn't notice the last bit of the message.... this doesn't rely on Steams API by any means.... and the documentation is very clear on how to setup this application. However, if you do not have the basic knowledge in coding / running a nodejs application / ect. then you'll need to do some research online before assuming something you don't know much about.

definitely directly affects it. qb runs on license key numbers. to allow players to join from steam i would need to set an api key(without it players cannot join) that would confuse my db as it would start mixing up steam and license numbers. only been doing this 4 years. but what the fuck do i know.
