### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by DegenTheo** [TheONLYGod1/FivemServerStatus#14]
Gets stuck on this 
![image](https://user-images.githubusercontent.com/45525477/173597978-6d048b2e-da9f-4e61-9983-a3829ca56a1d.png)

**Comment by DegenTheo** [comment]
Changed the IP in the config now it gets stuck on this 
![image](https://user-images.githubusercontent.com/45525477/173599035-68061a53-1b18-46e2-903e-06295fd17f8e.png)

**Comment by TheONLYGod1** [comment]
It's most likely due to the newest API update from discord. I need to update this repo. It'll probably be later this week when I get time to update it

**Comment by DegenTheo** [comment]
> It's most likely due to the newest API update from discord. I need to update this repo. It'll probably be later this week when I get time to update it

Okay sounds good. Ill keep an eye out for the update :)

**Comment by TheONLYGod1** [comment]
Yea I apologize for the time it's taken but I've been super busy with IRL stuff and my discord bot D: but don't worry this will be update either later today or sometime tomorrow

**Comment by DegenTheo** [comment]
> Yea I apologize for the time it's taken but I've been super busy with IRL stuff and my discord bot D: but don't worry this will be update either later today or sometime tomorrow

Oh don't worry man take your time :)
