### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DayRK** [TheONLYGod1/FivemServerStatus#17]
![image](https://user-images.githubusercontent.com/34480038/181569237-7464b98e-8267-4f82-94fa-2e9b2a6309f4.png)
Then it starts not to update the embedded message in discord

**Comment by TheONLYGod1** [comment]
Somethings wrong with your bot token. Try regenerating it.

**Comment by TheONLYGod1** [comment]
Issue has been explained with the most recent commit to the readme file
