### ISSUE TITLE
 node-fetch was unable to get server info... Error: undefined

### ISSUE THREAD

**Issue by Shafat21** [TheONLYGod1/FivemServerStatus#18]
node-fetch was unable to get server info...
Error: undefined

What can be the reason?

![image](https://user-images.githubusercontent.com/61838416/206888693-5eac0313-b99e-4b7a-8ce5-6dfd54100bc0.png)

**Comment by TheONLYGod1** [comment]
Are you using the latest version of the project?

**Comment by Shafat21** [comment]
Yes 4.2.2 which is 4.2.1 on package.json

**Comment by TheONLYGod1** [comment]
Sorry for the late reply, please make sure you are able to access, in a web browser, http://[serverip]:[serverport]/players.json. If you are not able to, please make sure you do not have a firewall blocking that port.

**Comment by TheONLYGod1** [comment]
I am sorry I just looked over your error again and I noticed it is a node-feitch timeout seen by line 51-69 in bot.js. You can ignore this error unless it is causing other issues. Also if it is still causing you issues you can increase the time between fetching in bot.js line 40.

Line 40:  const UPDATE_TIME = 10000; // in ms

**Comment by Shafat21** [comment]
Close
