### ISSUE TITLE
bot cannot start

### ISSUE THREAD

**Issue by JeffreyKroonenberg** [TheONLYGod1/FivemServerStatus#19]
Bot cannot start because the program to be downloaded no longer exists

**Comment by TheONLYGod1** [comment]
Sorry for the late response. Can you show a screenshot of this please? It's hard to assist without an image of the error or an actual error to reference.

**Comment by BillyFriendTTV** [comment]
https://i.imgur.com/ST8u1Pu.png

**Comment by TheONLYGod1** [comment]
Please join the support server I am no longer assisting with issues here on github. When you join please create a new ticket and I can assist you there https://discord.gg/pAKE2YK .
