### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by tiboorr** [TheONLYGod1/FivemServerStatus#20]
Hello. I am on linux ubuntu server and i set up config.json
When i try to npm install like instructions says at first looks fine but then some errors show.
errors in console: https://pastebin.com/z6Rp9u2c
npm-debug.log : https://store11.gofile.io/download/6eb1c9d8-1b1e-4e5c-b1ff-430da4939390/npm-debug.log

Hope this logs help resolve issue.

**Comment by TheONLYGod1** [comment]
Please join the support server I am no longer assisting with issues here on github. When you join please create a new ticket and I can assist you there https://discord.gg/pAKE2YK .
