### ISSUE TITLE
[SPAM] Update Was succesfsul

### ISSUE THREAD

**Issue by Grant-K** [TheONLYGod1/FivemServerStatus#21]
How do i stop the console from spamming Update was successful every 15 seconds?

**Comment by PurchasedGaming** [comment]
Please Comment out both lines 115 & 127 as followed:

115   //console.log(`${chalk.bgMagenta(`[SPAM]`)} ${chalk.magenta(`Update was successful`)}`)
127  //console.log(`${chalk.bgMagenta(`[SPAM]`)} ${chalk.magenta('Embed update successful')}`)


This should disable any update messages which is classed as spam, rest assured there will be an update soon to enable and disable it via config.
