### ISSUE TITLE
Bot still wont update server status.

### ISSUE THREAD

**Issue by icallhertaco** [TheONLYGod1/FivemServerStatus#6]
The bot connects fine no errors but it just always says my server is offline when it isn't. 
![image](https://user-images.githubusercontent.com/92546796/137382207-8e29e3ba-e0ca-40ff-a69e-6d494d896b99.png)
![image](https://user-images.githubusercontent.com/92546796/137382245-dfefa58a-6ff9-486d-bb51-1bac8da6f89e.png)
![image](https://user-images.githubusercontent.com/92546796/137382279-12b279f3-a296-44c4-bc1a-05640bba359a.png)

**Comment by TheONLYGod1** [comment]
> The port is required

http://ip:port
